Update error

diff --git a/error b/error
--- a/error
+++ b/error
@@ -1,17 +1,11 @@
-0s
-Run if [ ! -d "../enterprise-ansible-roles" ]; then
-/ansible/GITHUB_RUNNER/actions-runner10/_work/_temp/697a8fb8-d3fa-4a6d-9381-d104595c39ee.sh: line 2: git: command not found
-Error: Process completed with exit code 127.
-
-this is my workflow
 name: Deploy Database
 
 on:
   workflow_dispatch:
-   inputs:
+    inputs:
       compile_date:
         description: 'Compile date to deploy'
-        required: true 
+        required: true
         type: string
 
 jobs:
@@ -19,16 +13,24 @@ jobs:
     runs-on: 
       group: rakbank-self-hosted-runner
       labels: dehitdevtra1
-   
 
     steps:
+      - name: Install Git
+        run: |
+          if ! command -v git &> /dev/null
+          then
+            echo "Git not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y git
+          else
+            echo "Git is already installed."
+          fi
+
       - name: Checkout mcf_db repository
         uses: actions/checkout@v2
         with:
           repository: rakbank-internal/mcf_db
           ref: ${{ github.event.inputs.branch }}
-
-    
 
       - name: Clone enterprise-ansible-roles repository
         run: |
@@ -52,3 +54,4 @@ jobs:
         run: |
           cd ${{ github.workspace }}
           ansible-playbook -vvv -b -i inventory.ini ./playbook/mcfdbdeployment.yml --extra-vars "target=oracle_servers destination=${{ github.workspace }}"
+
